version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"
  npm-registry-npm-goodeggs-com:
    type: npm-registry
    url: https://npm.goodeggs.com
    token: "${{secrets.NPM_REGISTRY_NPM_GOODEGGS_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 27
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.13.12
    - 7.13.8
  registries:
  - npm-registry-registry-npmjs-org
  - npm-registry-npm-goodeggs-com
