sudo: required
dist: trusty
language: node_js
node_js:
- 14.21.3

cache:
  yarn: true
  directories:
  - "/home/travis/.npm"
  - "/tmp/ci-tools"
  - "node_modules"

env:
  global:
  - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"
  - NODE_ENV=test
  - FORCE_LOGS=yes

before_install:
- curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=1.9.4
script: yarn test
jobs:
  include:
    # Install dependencies and save them to the Travis cache
    - stage: "Install dependencies"
      # Don't run `script`, just install dependencies
      before_script: skip
      script: skip
    # Run tests
    - stage: "Test"
      name: "Lint"
      script: yarn run lint
    - name: "Type Checking"
      script: yarn run typecheck
    - name: "Unit Tests"
      script: yarn run test:unit
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    # Publish tags
    - stage: "Publish to registry"
      if: tag =~ ^v
      script: skip
      deploy:
        provider: npm
        email: open-source@goodeggs.com
        api_token:
          secure: "dp3OCYC30Uig3xlG0LmSRFC4Tr/FbeQUCpsNBKCFvkdosKCUnMi6jx0+xy13rVIm8edBQ+1PJbibvEPNRyXh0Qh+xQVQ3QpjJgoUwERxFv/mPIKUjTsUmy/vTa59MYSs9LQusOYdtsrW2L/wgcFsdwXoAZKOi1GY1MFgqwsAOhw3Il3g/RtLCNGr5LRpH5AZn6FOrU9URKdeCkIOvK6iH2f0lF9czx9j+woRsqN8oTOjK+oXbqv19lM4CvJ8sj6D/MXEnO5JXMLCjgcWEfgHbpHD+0vTz1IWscYPsDvkP7snzulLxJZ1rF1ZmppuIe5QJgzcv7cbpphcw6RaRsZCDLElVwYFTEA8rp8MQBLJ1vMeDTRDH3kwgiQNRiU67BEhyEPdjAsrAdEMFjCX7v3BnlHL+jky7fMkAh9HTxxF+DcNcm0LR8RudrmPqUROFFFoGqQuKM0TH+zImUWkh8OpbE509I9WiTaNG3pM/wR/ArugA3VVQ+YgJKaStrqa4G6RnWx/FifIjlgnKfHY2YOGWtjOepB2doTNxXrngTckEuXFUj/egHONB6PmyOM0sycS3emdQXZpcJbrhI968pp6y1RPjsvxYuLYLsQU84VouHtnnupUfTcKuqrQFatK5KDj1P21xxPWi/pPS7MP3Mz+pn3i78A2IMoZ9tGojY/AjqE="
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
